version: '3.3'
services:
    dockerpuppet:
        environment:
            - SERVERCERT=puppetserver.hetzner.company
            - AUTOSIGN=true
        build: .
        ports:
            - '8140:8140'
        container_name: dockerpuppet
        volumes:
            - ./environment/_data/production:/etc/puppetlabs/code/environments/production/
        image: 'dockerpuppet:latest'
